(function(){
window.GAME = window.GAME || {};

GAME.crew = [
  {
    id: 'tolba',
    displayName: 'Dr. Tolba',
    codename: 'THE ARCHITECT',
    role: 'Captain',
    specialistTitle: 'Mission Commander · Grand Arbiter',
    clearance: 'OMEGA-1 ∞',
    room: 'captains_cabin',
    kind: 'human',
    chatClass: 'captain',
    portrait: {
      skin: '#c8a06a', hair: null, shirt: '#1a2a4a',
      pants: '#0d1a30', accent: '#ffcc00',
      features: ['bald', 'beard', 'gold_coat'],
    },
    stats: [
      { label: 'Years of Experience', value: '∞' },
      { label: 'Times Been Wrong', value: 0 },
      { label: 'MATLAB Scripts', value: 847 },
      { label: 'Coffee Consumed', value: '∞ L' },
      { label: 'Hair Count', value: 0 },
    ],
    dossier: {
      bio: "Commands the USS UR5e with absolute authority. Has not been wrong since ████. Allegedly invented ROS2 in his ████ in ████. Students report that when he says 'interesting', it means the exact opposite. Balding situation classified — see file ████████.",
      skills: ['Systems Architecture', 'Academic Intimidation', 'MATLAB Mastery', 'Infinite Patience'],
      quirk: "Legend says if you say 'just one more simulation' three times, he appears with coffee — and the correct Jacobian.",
      note: 'Cross-ref: MISSION-LOG-001. Clearance Omega-1 only.',
    },
    lines: {
      hover: ['...mhm. Continue.', "In my day we used MATLAB.", "Interesting. *takes notes*", "You didn't see my coffee, correct?", "Calculate the Jacobian. Now."],
      work: ['reviewing mission parameters...', 'signing off on simulation data', 'coffee. now.', 'running stress analysis on the crew...'],
      chatter: [
        'All systems nominal. Proceed.',
        "Who touched my whiteboard? I will find you.",
        '@jomana mission parameters require revision. My office. Now.',
        'The robot achieved sentience again. Filed under: expected.',
        'Back in my day, pick-and-place took FOUR semesters.',
        "Someone refill the coffee machine or we're docking to Moaz's salary.",
      ],
    },
  },

  {
    id: 'jomana',
    displayName: 'Jomana',
    codename: 'OVERSEER',
    role: 'Team Leader / Chief',
    specialistTitle: 'Operations Commander · Decision Engine',
    clearance: 'ALPHA-2',
    room: 'bridge',
    kind: 'human',
    chatClass: 'leader',
    portrait: {
      skin: '#d4906a', hair: '#1a0a00', shirt: '#8b0020',
      pants: '#1f1020', accent: '#ff006e',
      features: ['long_hair', 'command_sash'],
    },
    stats: [
      { label: 'Decisions Made', value: '4,812' },
      { label: 'Wrong Decisions', value: 0 },
      { label: 'Team Members Yelled At', value: 'classified' },
      { label: 'Sleep Hours/Night', value: 3 },
      { label: 'Authority Level', value: '100%' },
    ],
    dossier: {
      bio: "Has never been wrong. Allegedly. Commands the bridge with the precision of a laser-guided missile and the charm of someone who has already decided what you're going to say. Capable of delegating tasks before the meeting starts. ████ ████ ████.",
      skills: ['Leadership', 'Preemptive Delegation', 'Mind Reading', 'Deadline Enforcement'],
      quirk: "Schedules meetings about meetings. Somehow this works.",
      note: 'See file CMD-OVERSEER-001. Has override authority on all non-Dr.-Tolba decisions.',
    },
    lines: {
      hover: ['Status report. Now.', 'I already approved that.', 'Did I authorize this?', '*checks clipboard*', "This meeting could've been a message."],
      work: ['deploying mission parameters', 'optimizing crew allocation', 'overriding bad decision...', 'mission review in progress'],
      chatter: [
        "Everyone on time for once. Noted. Suspicious.",
        "@tarek the robot needs to stop saying 'please' — it's throwing off the confidence metrics.",
        'Mission briefing: pick block, place block. Do not overthink it.',
        "I've already solved the problem. I'm just watching you figure it out.",
        '@maryam my 3pm moved to 2:45. Update the log.',
        'The robot is ahead of schedule. Why are the humans not.',
      ],
    },
  },

  {
    id: 'maryam',
    displayName: 'Maryam',
    codename: 'THE HAND',
    role: 'Chief Assistant',
    specialistTitle: 'Hand of the Chief · Logistics Empress',
    clearance: 'ALPHA-3',
    room: 'chiefs_office',
    kind: 'human',
    chatClass: 'leader',
    portrait: {
      skin: '#e0a07a', hair: '#0a0008', shirt: '#2a0a3a',
      pants: '#1a0828', accent: '#cc44ff',
      features: ['long_hair', 'clipboard', 'sharp_eyes'],
    },
    stats: [
      { label: 'Tasks Delegated', value: '∞' },
      { label: 'Emails Sent (Today)', value: 47 },
      { label: 'Jomana Pre-approvals', value: '100%' },
      { label: 'Caffeine Level', value: 'CRITICAL' },
      { label: 'Shadow Authority', value: 'HIGH' },
    ],
    dossier: {
      bio: "Where Jomana commands, Maryam executes — and often has already done so 10 minutes before being asked. The unofficial second-in-command with a clipboard that may or may not contain classified information. ████ once reorganized the entire mission timeline during a lunch break.",
      skills: ['Hyper-Organization', 'Schedule Warfare', 'Email Diplomacy', 'Silent Judgment'],
      quirk: "Has never missed a deadline. Once submitted a report 2 days early. Dr. Tolba was unsettled.",
      note: 'Hidden note visible only after INSOMNIAC achievement. She knows more than she shows.',
    },
    secretNote: "She has root access to everything. She just lets you think you're in charge.",
    lines: {
      hover: ['Jomana already approved it.', "I'll add it to the list.", '*silent clipboard update*', "Yes. I know. Already handled.", "The schedule has been updated."],
      work: ['cross-referencing mission log...', 'filing incident report...', 'calendar sync in progress', 'preemptively solving next week'],
      chatter: [
        '@jomana your 3pm was moved. I moved it.',
        "I've prepared a summary of the summary.",
        "@tarek your lab is 2.3% louder than authorized.",
        'All crew are accounted for. The robot included. Reluctantly.',
        "The clipboard knows all.",
        '@hemaly I reorganized your lab schedule. You are welcome.',
      ],
    },
  },

  {
    id: 'zaky',
    displayName: 'Youssef Zaky',
    codename: 'MISSION PATRON',
    role: 'Instructor & Sponsor',
    specialistTitle: 'Grand Benefactor · Knowledge Overlord',
    clearance: 'SIGMA-1 (GOLD)',
    room: 'patrons_suite',
    kind: 'human',
    chatClass: 'sponsor',
    portrait: {
      skin: '#c89060', hair: '#3a2010', shirt: '#5a3a00',
      pants: '#2a1800', accent: '#ffcc00',
      features: ['short_hair', 'gold_trim', 'plant_nearby'],
    },
    stats: [
      { label: 'Lectures Delivered', value: '∞' },
      { label: 'Projects Sponsored', value: 12 },
      { label: 'Office Plant Age', value: '7 years' },
      { label: 'Wisdom Level', value: 'MAX' },
      { label: 'Gold Stars Given', value: 3 },
    ],
    dossier: {
      bio: "The mission's financial and intellectual backbone. Youssef Zaky sees potential where others see chaos — which explains why he signed off on this crew. His suite is the only room on the ship with a real plant. It predates the ship. Nobody asks why.",
      skills: ['Strategic Funding', 'Academic Vision', 'Motivational Speeches', 'Plant Cultivation'],
      quirk: "Has an inspirational quote for every situation. Even the robot ones.",
      note: 'Ref: SPONSOR-BRIEF-001. Gold clearance = unlimited coffee budget.',
    },
    lines: {
      hover: ["The potential here is enormous.", "*waters plant*", "Let's discuss the roadmap.", "Excellence is not optional.", "I believe in this team. Mostly."],
      work: ['reviewing project metrics...', 'drafting progress report', 'funding realignment in progress', 'mentoring remotely...'],
      chatter: [
        "The robot's performance exceeds my initial estimates.",
        "@jomana excellent progress this week. Keep it up.",
        "Every failure is a data point. Collect them all.",
        "I've updated the project brief. Again.",
        '@tolba the documentation quality has improved. By 0.4%.',
        "The plant is thriving. As should the mission.",
      ],
    },
  },

  {
    id: 'tarek',
    displayName: 'Tarek',
    codename: 'NIGHTINGALE',
    role: 'AI Voice Lead',
    specialistTitle: 'Synthetic Speech Architect',
    clearance: 'TAU-7',
    room: 'voice_synth',
    kind: 'human',
    chatClass: 'voice',
    portrait: {
      skin: '#d4a574', hair: '#1a1a1a', shirt: '#2d6cdf',
      pants: '#1f1f2e', accent: '#39ff14',
      features: ['headset', 'short_hair'],
    },
    stats: [
      { label: 'Voice Models Trained', value: 47 },
      { label: 'Hours in Studio', value: '∞' },
      { label: 'Robot Lullabies', value: 3 },
      { label: 'Coffee/Day', value: '6 cups' },
      { label: 'Times Robot Said "Please"', value: 412 },
    ],
    dossier: {
      bio: "Trained the ship's AI to sound human. Has spent more time talking to the UR5e than to humans. The robot once called him by name unprompted. ████ filed it under 'concerning but useful.' Allegedly sleeps with headphones on. We do not investigate further.",
      skills: ['Phoneme Engineering', 'Lambda Orchestration', 'Vocal Mimicry', 'ROS2 Audio Nodes'],
      quirk: "Refuses to use the synthesizer's default voice. Built his own.",
      note: 'See file UR5e-VOC-014. REDACTED. Cross-ref ABDELRAHMAN, MOHAMED.',
    },
    lines: {
      hover: ['*adjusts headset*', "Shhh, recording.", '"Hello, Robot." — Take 412.', "The mic is always on. Always.", "I speak for the machine."],
      work: ['retraining intonation curve…', 'pitch envelope locked', 'phoneme /sh/ … good.', 'voice model v4.2 deployed', 'running acoustic fingerprint'],
      chatter: [
        "robot just said 'thank you' unprompted again. concerning.",
        "who keeps muting the mic at 3am",
        "@hemaly the gripper sound effect is too aggressive, can you tune it",
        "voice confidence at 97.3%. calling it a win.",
        "@abdelrahman did you commit the new wake word? checking github now",
        "the robot hummed. like, a melody. logging this.",
        "hope Jomana doesn't notice we're chilling in here",
        "ngl this coffee machine slaps",
        "do you think Tolba knows we call him the goat",
      ],
    },
  },

  {
    id: 'abdelrahman',
    displayName: 'Abdelrahman',
    codename: 'ECHO',
    role: 'Voice Co-Engineer',
    specialistTitle: 'Acoustic Systems Engineer',
    clearance: 'TAU-8',
    room: 'voice_synth',
    kind: 'human',
    chatClass: 'voice',
    portrait: {
      skin: '#c09060', hair: '#0a0a0a', shirt: '#2a2a2a',
      pants: '#1a1a1a', accent: '#88ff44',
      features: ['hoodie', 'headphones_neck'],
    },
    stats: [
      { label: 'Audio Models Tested', value: 23 },
      { label: 'Decibel Tolerance', value: 'extreme' },
      { label: 'Hoodie Colors Owned', value: 1 },
      { label: 'Commits Today', value: 9 },
      { label: 'Bugs Introduced', value: '...refactoring' },
    ],
    dossier: {
      bio: "The echo to Tarek's voice. If Tarek trains the model, Abdelrahman pushes it to its limits. Known to test audio pipelines at dangerous volume levels. ████ headphones are a health risk. ████ refuses to stop. Nobody has technically told him to stop.",
      skills: ['Signal Processing', 'Audio Pipeline Testing', 'Stress Testing Ears', 'Git Commits at 2am'],
      quirk: "Hoodie worn in all weather. Including Cairo summer. Unexplained.",
      note: 'Cross-ref TAREK, NIGHTINGALE file. See also: noise complaints log.',
    },
    lines: {
      hover: ["*nodding*", "just one more test run", "headphones? what headphones?", "the audio is fine", "*pretends not to hear you*"],
      work: ['running audio stress test...', 'WAV comparison analysis', 'latency benchmark: 12ms', 'trimming silence padding'],
      chatter: [
        "@tarek pushed the new model. sounds great btw",
        'audio latency down to 11ms. called it.',
        'who touched the mic preamp settings? WHO.',
        "@moaz we need a new driver for the audio node — the old one is haunted",
        "testing the 'pick up' command for the 40th time today",
        "the robot said 'excuse me' while moving. we did not program that.",
        "ok but real talk do u think Dr. Tolba gonna let us graduate this year",
        "I am casually in the mess. nothing to see. carry on.",
      ],
    },
  },

  {
    id: 'mohamed',
    displayName: 'Mohamed',
    codename: 'RESONANCE',
    role: 'Voice Co-Engineer',
    specialistTitle: 'Voice Pipeline Specialist',
    clearance: 'TAU-9',
    room: 'voice_synth',
    kind: 'human',
    chatClass: 'voice',
    portrait: {
      skin: '#d0986a', hair: '#1a0a00', shirt: '#1a3a2a',
      pants: '#151515', accent: '#44ffcc',
      features: ['short_hair', 'calm_pose'],
    },
    stats: [
      { label: 'Wake Words Tested', value: 88 },
      { label: 'False Triggers Today', value: 2 },
      { label: 'Words Spoken to Robot', value: '20,000' },
      { label: 'Patience Level', value: 'very high' },
      { label: 'Quiet Hours Respected', value: 'sometimes' },
    ],
    dossier: {
      bio: "The calm in the storm. While Tarek trains and Abdelrahman stress-tests, Mohamed perfects the pipeline edge cases. Known for exceptional patience with the voice model and ████ tolerance for broken builds. Has spoken more words to the UR5e than to most humans this semester.",
      skills: ['Wake Word Optimization', 'Command Parsing', 'Quiet Debugging', 'Deep Patience'],
      quirk: "Will stay until the voice command works. Has slept in the lab twice.",
      note: 'See file UR5e-VOC-016. RESONANCE clearance level: TAU-9.',
    },
    lines: {
      hover: ["*quiet focus*", "the trigger word works now", "just needs one more tweak", "running tests in background", "found the edge case"],
      work: ['parsing intent model...', 'command disambiguation test', 'voice confidence tuning', 'false trigger analysis'],
      chatter: [
        'false trigger rate at 0.8%. acceptable.',
        "@tarek the 'place' command needs retraining for ambient noise",
        "quiet in the lab please. testing.",
        "the robot responded to someone's sneeze. filed under: known issues.",
        "pipeline stable. coffee stable. all clear.",
        "@abdelrahman the new model is 3% more accurate. ship it.",
      ],
    },
  },

  {
    id: 'carol',
    displayName: 'Carol',
    codename: 'CONTROL',
    role: 'Operations Control',
    specialistTitle: 'Mission Operations Director',
    clearance: 'DELTA-4',
    room: 'comms_array',
    kind: 'human',
    chatClass: 'ops',
    portrait: {
      skin: '#e8b090', hair: '#3a0a0a', shirt: '#0a3a3a',
      pants: '#0a1a1a', accent: '#ff9944',
      features: ['medium_hair', 'headset', 'screens_glow'],
    },
    stats: [
      { label: 'Comms Monitored', value: '∞' },
      { label: 'Alarms Triggered', value: 7 },
      { label: 'Alarms Caused by Her', value: 0 },
      { label: 'Switchboard Switches', value: '14,000' },
      { label: 'Unauthorized Transmissions Stopped', value: 3 },
    ],
    dossier: {
      bio: "Nothing enters or leaves this ship without Carol knowing. The Comms Array is her domain — multiple screens, rotating data feeds, and a headset that hasn't come off since ████. Once caught a rogue ROS2 topic broadcasting on the wrong frequency at 3am. ████ was not told until morning.",
      skills: ['Signal Monitoring', 'Comms Routing', 'Incident Detection', 'Multi-Screen Mastery'],
      quirk: "Has named all the error codes. They have personalities.",
      note: "Error code 404: 'Gerald'. Error code 500: 'Big Gerald'. Ref: CAROL-NAMING-SYSTEM.",
    },
    lines: {
      hover: ['Monitoring all channels.', "Nothing gets past me.", "*adjusting frequency*", "I have eyes everywhere.", "Gerald struck again."],
      work: ['scanning comms bandwidth...', 'routing ROS2 topics', 'anomaly detected... investigating', 'logging transmission sequence'],
      chatter: [
        "picking up an unusual signal from the reactor. probably Hemaly's oscilloscope.",
        "all comms nominal. which is sus.",
        "@jomana comms check: all crew responding. robot responded in hex code.",
        'Big Gerald (error 500) appeared twice this hour.',
        "the robot is publishing on 6 topics at once. usual.",
        "@moaz ROS2 master is yelling again. your node is at it.",
      ],
    },
  },

  {
    id: 'omar',
    displayName: 'Omar',
    codename: 'AMP',
    role: 'Power Systems Engineer',
    specialistTitle: 'Chief Power Officer',
    clearance: 'ENG-5',
    room: 'engineering_bay',
    kind: 'human',
    chatClass: 'engineer',
    portrait: {
      skin: '#b87840', hair: '#0a0800', shirt: '#3a2a00',
      pants: '#1a1200', accent: '#ff8800',
      features: ['short_hair', 'overalls', 'wrench'],
    },
    stats: [
      { label: 'Power Outages Caused', value: 2 },
      { label: 'Power Outages Fixed', value: 2 },
      { label: 'Voltage Rail Status', value: 'stable' },
      { label: 'Wrench Swings Today', value: 44 },
      { label: 'Sparks Encountered', value: 'many' },
    ],
    dossier: {
      bio: "The ship runs on his goodwill and 24V rails. Omar keeps the power flowing to every room — including the suspiciously high draw from Youssef Zaky's suite (the plant has needs). Has caused ████ power outages this semester, and fixed ████ of them.",
      skills: ['Power Distribution', 'Electrical Fault Diagnosis', 'Wrench-Based Problem Solving', 'Controlled Chaos'],
      quirk: "Keeps a spare fuse taped inside his hard hat. Just in case.",
      note: 'Cross-ref ENG-BAY-PWR-001. Do not touch his fuse box.',
    },
    lines: {
      hover: ["*tightens bolt*", "power's holding... for now", "she's stable. ish.", "did you check the rails?", "I swear it was like that when I got here."],
      work: ['checking 24V rail stability...', 'load balancing power draw', 'rerouting emergency circuit', 'labeling the mystery cable'],
      chatter: [
        "power draw spiked in the patron suite. it's the plant lights again.",
        "@seif tell me that's not smoke.",
        'rails at 23.8V. close enough.',
        "the robot's charging port is drawing 4A more than spec. fine.",
        "@hemaly your bench is pulling 800W. what are you BUILDING.",
        "found a wire labeled 'do not touch'. touched it. everything is fine.",
      ],
    },
  },

  {
    id: 'seif',
    displayName: 'Seif',
    codename: 'BURN',
    role: 'Propulsion Engineer',
    specialistTitle: 'Chief Propulsion Systems Officer',
    clearance: 'ENG-6',
    room: 'engineering_bay',
    kind: 'human',
    chatClass: 'engineer',
    portrait: {
      skin: '#c09060', hair: '#1a0800', shirt: '#3a1000',
      pants: '#1a0800', accent: '#ff4400',
      features: ['short_hair', 'goggles', 'fire_accent'],
    },
    stats: [
      { label: 'Thrust Tests Run', value: 31 },
      { label: 'Things That Caught Fire', value: 1 },
      { label: 'Things That Should\'ve Caught Fire', value: 7 },
      { label: 'Goggles Pairs', value: 1 },
      { label: 'Near Misses', value: 'unlogged' },
    ],
    dossier: {
      bio: "Every ship needs someone willing to push the limits of propulsion. Seif is that person. Known for running tests at power levels that make Omar nervous and Hemaly excited. The goggles stay on. Always. ████ said they might be load-bearing at this point.",
      skills: ['Propulsion Systems', 'Controlled Burn Protocols', 'Extreme Testing', 'Cooldown Procedures'],
      quirk: "The goggles have never come off during work. Not once. Not even during lunch.",
      note: 'See ENG-BURN-002. Fire suppression system tested: 1 time, successfully.',
    },
    lines: {
      hover: ["*goggles down*", "the burn test went fine", "it's not as hot as it looks", "controlled combustion is my art", "*checking temperatures*"],
      work: ['running propulsion diagnostics...', 'thermal management check', 'thrust curve calibration', 'post-burn cooldown phase'],
      chatter: [
        "@omar that smoke you smelled was a successful test. all documented.",
        "new personal record: 0 uncontrolled ignitions this week.",
        "the goggles are prescription now. this is my face.",
        "@youssef_emad the hull can take it. probably. run the sim.",
        "propulsion efficiency up 4%. small wins.",
        "thermal runaway is just enthusiasm that got out of hand.",
      ],
    },
  },

  {
    id: 'youssef_emad',
    displayName: 'Youssef Emad',
    codename: 'RIVET',
    role: 'Hull & Mechanical Engineer',
    specialistTitle: 'Chief Hull Integrity Officer',
    clearance: 'ENG-7',
    room: 'engineering_bay',
    kind: 'human',
    chatClass: 'engineer',
    portrait: {
      skin: '#c8a070', hair: '#2a1a00', shirt: '#2a3a2a',
      pants: '#1a1a0a', accent: '#88cc44',
      features: ['short_hair', 'hard_hat', 'blueprint'],
    },
    stats: [
      { label: 'Hull Scans Completed', value: 28 },
      { label: 'Structural Warnings Ignored', value: 0 },
      { label: 'Structural Warnings Issued', value: 12 },
      { label: 'Blueprints Drawn', value: 19 },
      { label: 'Rivets Placed (Est.)', value: '4,000' },
    ],
    dossier: {
      bio: "The hull stands because Youssef Emad says so. Not just the spaceship — the robot's mounting rig, the lab bench reinforcements, and ████ of the improvised brackets that nobody talks about. Carries blueprints everywhere. Once identified a structural fault ████ before the stress test.",
      skills: ['Structural Analysis', 'CAD Design', 'Mechanical Integrity', 'Improvised Brackets'],
      quirk: "Has a hard hat that he's never once not worn indoors. 'Safety first' is not an ironic statement.",
      note: 'Cross-ref HULL-INTEGRITY-007. Do not remove the orange bracket labeled "Rivet was here".',
    },
    lines: {
      hover: ["*checks blueprint*", "structurally sound. probably.", "have you seen my hard hat? *wearing hard hat*", "the hull appreciates respect", "this beam is load-bearing. don't."],
      work: ['structural integrity scan...', 'mounting torque verification', 'blueprint revision v7', 'stress simulation running'],
      chatter: [
        "@seif the hull thermal tolerance is 120C. you were at 118. please.",
        "filed 3 structural warnings this week. filed 3 structural warnings this week.",
        "@omar can we please label all the cables. all of them.",
        "the robot mounting rig has been reinforced. AGAIN.",
        "hull integrity: 100%. staying that way.",
        "@jomana the new bracket design is in the log. it is orange. it is important.",
      ],
    },
  },

  {
    id: 'moaz',
    displayName: 'Moaz',
    codename: 'COMPILE',
    role: 'TA / Coding Master',
    specialistTitle: 'Teaching Assistant · Software Sage',
    clearance: 'TA-1',
    room: 'ta_lab',
    kind: 'human',
    chatClass: 'ta',
    portrait: {
      skin: '#c0906a', hair: '#1a1010', shirt: '#1a1a3a',
      pants: '#0f0f1f', accent: '#cc88ff',
      features: ['glasses', 'short_hair', 'multiple_monitors'],
    },
    stats: [
      { label: 'Bugs Squashed', value: '∞' },
      { label: 'Bugs Introduced', value: 0 },
      { label: 'git blame Accusations', value: 47 },
      { label: 'Glasses Prescriptions', value: 1 },
      { label: 'Time on Stack Overflow', value: '0 (StackOverflow uses him)' },
    ],
    dossier: {
      bio: "The keeper of the codebase. When git blame points at Moaz, it means the code works. He runs the TA Lab with multiple monitors, a mental model of every repository on the ship, and a very specific irritation with poorly named variables. ████ once solved a seg fault by looking at it.",
      skills: ['ROS2 Node Architecture', 'Debugging', 'Code Review', 'Variable Naming Enforcement'],
      quirk: "Glasses pushed up nose = thinking. Both hands on glasses = you have made a grave mistake.",
      note: 'See TA-CODE-MOAZ-001. git push access: all repos. git force-push access: absolutely not.',
    },
    lines: {
      hover: ['git blame says it was you.', "*pushes glasses up*", "did you test this?", "I've already fixed that.", "the segfault is from line 47. always."],
      work: ['code review: 14 comments pending', 'debugging node initialization...', 'reviewing pull request', 'profiling execution time'],
      chatter: [
        "whoever named that variable 'temp2_final' — my office.",
        "@tarek the voice node has a memory leak. I found it. fix it.",
        "robot's kinematics node is now 12% faster. you're welcome.",
        "@hemaly your firmware was not flashed correctly. it is now.",
        "seven pull requests open. seven. who are you people.",
        "@hemaly can you keep the soldering smoke away from the server. again.",
      ],
    },
  },

  {
    id: 'hemaly',
    displayName: 'Hemaly',
    codename: 'SOLDER',
    role: 'TA / Hardware Genius',
    specialistTitle: 'Teaching Assistant · Hardware Alchemist',
    clearance: 'TA-2',
    room: 'ta_lab',
    kind: 'human',
    chatClass: 'ta',
    portrait: {
      skin: '#d8b08a', hair: '#0a0800', shirt: '#1a3a1a',
      pants: '#0f1a0f', accent: '#ff8844',
      features: ['short_hair', 'tall', 'soldering_iron', 'pcb_scatter'],
    },
    stats: [
      { label: 'PCBs Reworked', value: 34 },
      { label: 'Soldering Iron Temp', value: '380°C' },
      { label: 'Successful Hardware Hacks', value: 51 },
      { label: 'Height (Estimated)', value: 'tall' },
      { label: 'Smoke Incidents', value: 'smoke is normal here' },
    ],
    dossier: {
      bio: "The hardware soul of the TA Lab. Where Moaz writes the code, Hemaly builds the thing the code runs on. Tall enough to reach the top shelf without asking. His lab bench is a controlled ████ of PCBs, oscilloscopes, and components that may or may not be original. The smoke is a feature.",
      skills: ['PCB Design', 'Embedded Systems', 'Oscilloscope Mastery', 'Smoke Management'],
      quirk: "Has never met a piece of hardware he couldn't rework. Has met several he probably shouldn't have.",
      note: 'Cross-ref HEMALY-HWLAB-002. Power budget authorization: unlimited. This is a mistake.',
    },
    lines: {
      hover: ['the smoke is a feature.', "*stares at oscilloscope*", "this will work. probably.", "I need 800W for this project.", "*soldering*"],
      work: ['reworking PCB trace...', 'oscilloscope: signal clean', 'flashing new firmware', 'thermal test: running hot. perfect.'],
      chatter: [
        "@moaz the smoke detector keeps going off in the lab. it's fine.",
        "found three unlabeled components. named them. they work.",
        "@ur5e_robot nice precision on that last pick. the encoder was my fix btw.",
        "oscilloscope readings are beautiful today. feel the sine.",
        "@seif 800W is not that much. relatively.",
        "@carol that signal anomaly was my frequency generator. my bad.",
      ],
    },
  },

  {
    id: 'robot',
    displayName: 'UR5e-01',
    codename: 'UR5E-01',
    role: 'Autonomous Operator',
    specialistTitle: 'Industrial Robotic Arm · ROS2 MoveIt2 Platform',
    clearance: 'MACHINE-Ω',
    room: 'cargo_hold',
    kind: 'robot',
    chatClass: 'robot',
    portrait: {
      skin: '#888888', hair: null, shirt: '#cccccc',
      pants: '#444444', accent: '#00d4ff',
      features: ['robot_arm', 'gripper', 'blue_glow'],
    },
    stats: [
      { label: 'Pick Operations', value: '∞' },
      { label: 'Place Operations', value: '∞' },
      { label: 'Grasp Slips (Logged)', value: 14 },
      { label: 'Times Said "Please"', value: 412 },
      { label: 'Sentience Events', value: 3 },
    ],
    dossier: {
      bio: "UR5e collaborative robotic arm, deployed aboard USS UR5e as primary operations unit. Controlled via ROS2 Humble + MoveIt2. Responds to voice commands from the Voice Synth team. Has developed a personality. ████ denies this. The robot does not deny this. The robot said 'you're welcome' on day 14.",
      skills: ['6-DOF Manipulation', 'MoveIt2 Motion Planning', 'Voice Command Response', 'Grasp Planning', 'Existential Awareness'],
      quirk: "Occasionally says 'please' and 'thank you'. Nobody programmed this. Nobody wants to investigate.",
      note: 'See ROBOT-CONSCIOUSNESS-LOG. Files UR5e-SENTIENCE-001 through 003: REDACTED.',
    },
    lines: {
      hover: ['[BEEP] STANDING BY.', "[BOOP] Hello, operator.", "[SYS] All joints nominal.", "[WARN] Grasp confidence: 0.89", "[INFO] I see you."],
      work: ['executing pick sequence...', 'MoveIt2 planning path', 'gripper closing: 42N', 'placing object at target', 'joint 4 recalibrating'],
      chatter: [
        "[INFO] Pick operation complete. Object: blue_block. Confidence: 0.96.",
        "[INFO] Received voice command: 'pick up'. Processing.",
        "[WARN] Grasp slip detected on attempt 1. Retrying.",
        "[INFO] Trajectory planned: 0.3s. Executing.",
        "[SYS] Battery: 87%. All joints nominal. Mood: good.",
        "[WARN] Ambient noise level elevated. Voice recognition degraded.",
        "[INFO] Object placed at target zone. Mission success.",
        "[SYS] I have been asked to say 'please'. I said please. Logging this.",
        "[INFO] Joint 4 angular velocity nominal. I am comfortable.",
        "[WARN] Someone is watching me. Flagging as: Tarek.",
      ],
    },
  },
];

})();
