(function(){
window.GAME = window.GAME || {};

// ─── LAYOUT CONSTANTS (must be defined here — rooms.js loads before ai.js) ──
GAME.LAYOUT = {
  LOGICAL_W:  1440,
  LOGICAL_H:  810,
  TOP_BAR:    55,
  BOTTOM_BAR: 40,
  CORRIDOR_W: 28,
  CORRIDOR_H: 30,
  COLS: 4,
  ROWS: 3,
  CELL_W: 339,
  CELL_H: 218,
};

GAME.getRoomCell = function(room){
  var L = GAME.LAYOUT;
  return {
    x: room.col * (L.CELL_W + L.CORRIDOR_W),
    y: L.TOP_BAR + room.row * (L.CELL_H + L.CORRIDOR_H),
    w: L.CELL_W,
    h: L.CELL_H,
  };
};

// ─── ROOMS ──────────────────────────────────────────────────────────
GAME.rooms = [
  // ── ROW 0 ──────────────────────────────────────────────────────────
  {
    id: 'bridge',
    name: 'BRIDGE',
    subtitle: 'Command Center',
    col: 0, row: 0,
    colors: { bg: '#0e0020', border: '#ff006e', glow: '#ff006e', accent: '#ff44aa' },
    crew: ['jomana'],
    decor: ['console_large','screens_side','command_chair','tactical_map','status_board','mission_clock'],
    icon: '⚑',
    description: 'Mission command hub. All strategic decisions originate here.',
  },
  {
    id: 'captains_cabin',
    name: "CAPTAIN'S CABIN",
    subtitle: 'Restricted Access',
    col: 1, row: 0,
    colors: { bg: '#160f00', border: '#ffcc00', glow: '#ffcc00', accent: '#ffe066' },
    crew: ['tolba'],
    decor: ['desk_ornate','bookshelf','coffe_pot','whiteboard','diploma_wall','globe'],
    icon: '★',
    description: "The Captain's private domain. Knock twice. Wait.",
    isCaptain: true,
  },
  {
    id: 'comms_array',
    name: 'COMMS ARRAY',
    subtitle: 'Signal Control',
    col: 2, row: 0,
    colors: { bg: '#001414', border: '#ff9944', glow: '#ff9944', accent: '#ffbb66' },
    crew: ['carol'],
    decor: ['switchboard','multi_screens','antenna_dish','blinking_lights','signal_monitor','headset_hook'],
    icon: '📡',
    description: 'All communications routed here. Nothing escapes Carol.',
  },
  {
    id: 'patrons_suite',
    name: "PATRON'S SUITE",
    subtitle: 'Gold Clearance Only',
    col: 3, row: 0,
    colors: { bg: '#140e00', border: '#ffcc00', glow: '#ffd700', accent: '#ffee88' },
    crew: ['zaky'],
    decor: ['luxury_desk','plant_large','awards_shelf','coffee_premium','trophy_case','reading_lamp'],
    icon: '♛',
    description: 'Mission funding and academic oversight. Also: the good coffee.',
  },

  // ── ROW 1 ──────────────────────────────────────────────────────────
  {
    id: 'ta_lab',
    name: 'TA LAB',
    subtitle: 'Research & Debugging',
    col: 0, row: 1,
    colors: { bg: '#080016', border: '#9900ff', glow: '#9900ff', accent: '#cc66ff' },
    crew: ['moaz', 'hemaly'],
    decor: ['workbench_pcb','oscilloscope','server_rack','code_screen','soldering_station','multimeter'],
    icon: '⚙',
    description: 'Where bugs go to die and hardware is born. Both TAs required.',
  },
  {
    id: 'voice_synth',
    name: 'VOICE SYNTH BOOTH',
    subtitle: 'Audio Engineering',
    col: 1, row: 1,
    colors: { bg: '#001408', border: '#00ff88', glow: '#00ff88', accent: '#44ffaa' },
    crew: ['tarek', 'abdelrahman', 'mohamed'],
    decor: ['microphone','mixing_board','waveform_screen','sound_foam','headset_rack','studio_light'],
    icon: '🎙',
    description: 'The robot finds its voice here. Three engineers. One microphone.',
  },
  {
    id: 'chiefs_office',
    name: "CHIEF'S OFFICE",
    subtitle: 'Administration',
    col: 2, row: 1,
    colors: { bg: '#140014', border: '#cc44ff', glow: '#cc44ff', accent: '#ee88ff' },
    crew: ['maryam'],
    decor: ['desk_exec','filing_cabinet','clipboard_wall','org_chart','paper_stack','schedule_board'],
    icon: '♔',
    description: "Maryam's domain. The ship runs on her clipboard.",
  },
  {
    id: 'medbay_mess',
    name: 'MEDBAY / MESS',
    subtitle: 'Crew Rest & Recovery',
    col: 3, row: 1,
    colors: { bg: '#001410', border: '#00ccaa', glow: '#00ccaa', accent: '#44ffdd' },
    crew: [],
    decor: ['mess_table','coffee_machine_big','medbay_bed','snack_shelf','water_dispenser','first_aid'],
    icon: '✚',
    description: 'Social hub. Crew wanders here to eat, rest, and gossip.',
    isSocial: true,
    isChill: true,
    maxOccupants: 3,
  },

  // ── ROW 2 ──────────────────────────────────────────────────────────
  {
    id: 'engineering_bay',
    name: 'ENGINEERING BAY',
    subtitle: 'Structural & Power',
    col: 0, row: 2,
    colors: { bg: '#150800', border: '#ff6600', glow: '#ff6600', accent: '#ff9944' },
    crew: ['omar', 'seif', 'youssef_emad'],
    decor: ['power_board','tool_rack','blueprint_table','fuse_box','warning_lights','welding_rig'],
    icon: '⚡',
    description: 'Three engineers. Controlled chaos. The sparks are scheduled.',
  },
  {
    id: 'reactor_core',
    name: 'REACTOR CORE',
    subtitle: 'Automated Systems',
    col: 1, row: 2,
    colors: { bg: '#0a0010', border: '#ff2244', glow: '#ff2244', accent: '#ff6688' },
    crew: [],
    decor: ['reactor_cylinder','cooling_pipes','warning_tape','status_monitor','pressure_gauge','hazard_sign'],
    icon: '☢',
    description: 'Automated. Do not enter unless Hemaly says so.',
    isAutomated: true,
  },
  {
    id: 'cargo_hold',
    name: 'CARGO HOLD',
    subtitle: 'Robot Home Base',
    col: 2, row: 2,
    colors: { bg: '#001520', border: '#00d4ff', glow: '#00d4ff', accent: '#44eeff' },
    crew: ['robot'],
    decor: ['robot_dock','conveyor_belt','crates','pickup_zones','charging_port','block_storage'],
    icon: '🤖',
    description: 'Primary operations zone for UR5e-01. Pick-and-place operations run here.',
  },
  {
    id: 'airlock_observation',
    name: 'AIRLOCK / OBS.',
    subtitle: 'Scenic Overlook',
    col: 3, row: 2,
    colors: { bg: '#000308', border: '#4466ff', glow: '#4466ff', accent: '#88aaff' },
    crew: [],
    decor: ['space_window','airlock_door','star_view','telescope','observation_bench','deep_scanner'],
    icon: '🌌',
    description: 'Any crew member can visit. The stars are always out.',
    isSocial: true,
  },
];

// Build lookup map
GAME.roomMap = {};
GAME.rooms.forEach(function(r){ GAME.roomMap[r.id] = r; });

// ─── DECOR LABELS for hover tooltips ────────────────────────────────
GAME.DECOR_LABELS = {
  console_large:      'Main Command Console',
  screens_side:       'Tactical Display Screens',
  command_chair:      "Commander's Chair",
  tactical_map:       'Tactical Star Map',
  status_board:       'Mission Status Board',
  mission_clock:      'Mission Clock',
  desk_ornate:        "Captain's Ornate Desk",
  bookshelf:          'Academic Reference Shelf',
  coffe_pot:          'Coffee Pot (Sacred)',
  whiteboard:         'Whiteboard (Do Not Touch)',
  diploma_wall:       'Diploma & Credentials Wall',
  globe:              'Navigation Globe',
  switchboard:        'Comms Switchboard',
  multi_screens:      'Multi-Channel Display Array',
  antenna_dish:       'Signal Antenna Array',
  blinking_lights:    'Status Indicator Panel',
  signal_monitor:     'Signal Frequency Monitor',
  headset_hook:       'Headset Storage Hook',
  luxury_desk:        "Patron's Executive Desk",
  plant_large:        'The Plant (7 Years Old)',
  awards_shelf:       'Academic Awards Shelf',
  coffee_premium:     'Premium Coffee Station',
  trophy_case:        'Project Achievement Trophy',
  reading_lamp:       'Executive Reading Lamp',
  workbench_pcb:      'PCB Workbench',
  oscilloscope:       'Digital Oscilloscope',
  server_rack:        'Server & ROS2 Node Rack',
  code_screen:        'Code Review Monitor',
  soldering_station:  'Soldering Station (350°C)',
  multimeter:         'Digital Multimeter',
  microphone:         'Recording Microphone',
  mixing_board:       'Audio Mixing Board',
  waveform_screen:    'Waveform Analyzer',
  sound_foam:         'Acoustic Foam Panel',
  headset_rack:       'Headset Storage Rack',
  studio_light:       'Recording Studio Light',
  desk_exec:          "Chief's Executive Desk",
  filing_cabinet:     'Classified Filing Cabinet',
  clipboard_wall:     'Mission Clipboard Wall',
  org_chart:          'Crew Organization Chart',
  paper_stack:        'Pending Reports Stack',
  schedule_board:     'Mission Schedule Board',
  mess_table:         'Crew Dining Table',
  coffee_machine_big: 'Industrial Coffee Machine',
  medbay_bed:         'Medical Recovery Bed',
  snack_shelf:        'Crew Snack Shelf',
  water_dispenser:    'Water Dispenser',
  first_aid:          'First Aid Station',
  power_board:        'Primary Power Distribution Board',
  tool_rack:          'Engineering Tool Rack',
  blueprint_table:    'Blueprint Drafting Table',
  fuse_box:           'Main Fuse Panel',
  warning_lights:     'Emergency Warning Lights',
  welding_rig:        'Welding & Fabrication Rig',
  reactor_cylinder:   'Reactor Core Cylinder',
  cooling_pipes:      'Coolant Pipe System',
  warning_tape:       'Hazard Warning Tape',
  status_monitor:     'Reactor Status Monitor',
  pressure_gauge:     'Pressure Gauge Array',
  hazard_sign:        'Radiation Hazard Sign',
  robot_dock:         'UR5e-01 Docking Station',
  conveyor_belt:      'Automated Conveyor Belt',
  crates:             'Mission Object Storage Crates',
  pickup_zones:       'Pick-and-Place Target Zones',
  charging_port:      'Robot Charging Port',
  block_storage:      'Block Sorting Storage',
  space_window:       'Panoramic Space Window',
  airlock_door:       'Airlock Door (Secured)',
  star_view:          'Deep Space View Panel',
  telescope:          'Observation Telescope',
  observation_bench:  'Crew Observation Bench',
  deep_scanner:       'Deep Space Scanner',
};

})();
